CREATE DATABASE Task;

USE Task;

CREATE TABLE DEPARTMENT(
DNUM INT PRIMARY KEY , 
DName CHAR (60), 
SSN CHAR(9),
MANGEMENT_HIRE_DATE DATE
);

SELECT * FROM DEPARTMENT;

CREATE TABLE EMPLOYEE(
SSN CHAR (9) PRIMARY KEY,
FNAME NVARCHAR (30),
LNAME NVARCHAR (30),
GENDER CHAR (1),
BIRTHDATE DATE,
SUPERVISOR CHAR (9),
DNUM INT ,
FOREIGN KEY (SUPERVISOR) REFERENCES EMPLOYEE(SSN),
FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);

SELECT * FROM EMPLOYEE;

ALTER TABLE DEPARTMENT 
ADD CONSTRAINT MANAGER FOREIGN KEY(SSN) REFERENCES EMPLOYEE(SSN);

CREATE TABLE dependent (
Name NVARCHAR(60) PRIMARY KEY,
SSN CHAR(9),
GENDER CHAR(1),
BIRTHDATE DATE,
FOREIGN KEY (SSN) REFERENCES employee(SSN)
);


CREATE TABLE PROJECT(
PNUMBER INT PRIMARY KEY,
PNAME NVARCHAR(50),
LOCATION NVARCHAR(50),
CITY NVARCHAR(50),
DNUM INT,
FOREIGN KEY (DNUM) REFERENCES department(DNUM)
);

SELECT * FROM PROJECT
CREATE TABLE WORKON(
SSN CHAR(9),
PNUMBER INT,
WORKINGHOUR INT,
FOREIGN KEY (SSN) REFERENCES employee(SSN),
FOREIGN KEY (PNUMBER) REFERENCES PROJECT(PNUMBER)
);

SELECT * FROM dependent
CREATE TABLE DEARTMENTLOC(
LOCATION NVARCHAR(50) PRIMARY KEY,
DNUM INT,
FOREIGN KEY (DNUM) REFERENCES department(DNUM)
);

select * from EMPLOYEE
select * from DEPARTMENT
select * from PROJECT
select * from WORKON
select * from dependent	
select * from DEARTMENTLOC

